default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rehanity_38933_development


test:
  <<: *default
  database: rehanity_38933_test

production:
  <<: *default
  adapter: mysql2
  database: rehanity_38933_production
  username: root
  password: <%= ENV['REHANITY_38933_DATABASE_PASSWORD'] %>
